### ISSUE TITLE
React component

### ISSUE THREAD

**Issue by marcveens** [obiwanjacobi/Nova-System#1]
Kan hier ook een React component van gemaakt worden? Ik heb werkelijk geen idee wat er in deze repo staat, maar ik wil het graag in Javascript kunnen draaien

**Comment by obiwanjacobi** [comment]
Hahaha - hi Marc hoe gaatie?
Nee sorry, geen React voor deze repo. ;-)

**Comment by marcveens** [comment]
Heel jammer... 

Maar gaat goed! Ik heb sinds kort met een paar anderen in een opwelling een stukje land bij een volkstuintje gekocht, daar gaan we zelf een klein huisje bouwen. Eens wat anders dan websites knutselen...

Hoe is het met jou??

**Comment by obiwanjacobi** [comment]
Dat had ik nooit kunnen raden ;-) Huisje knutselen is altijd leuk.
Gaat lekker aan deze kant. Ben weer een beetje aan mijn compiler aan het klussen (Zsharp repo - src2/Maja folder).
